package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import control.ControllerCarrello;
import control.ControllerOrdini;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;

public class FormCarrello {
	private JPanel mainPanel;
	private JTable table_carrello;
	private JSpinner spinner_quantita;
	private JButton modificaButton;
	private JButton aggiornaButton;
	private JButton confermaButton;
	private JLabel label_totale;
	private JLabel label_esito;

	private final long idCliente;
	private JFrame frame;

	public FormCarrello(long idCliente) {
		this.idCliente = idCliente;
		spinner_quantita.setModel(new SpinnerNumberModel(1, 0, 999, 1));

		aggiornaButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				caricaCarrello();
			}
		});

		modificaButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				int rigaVista = table_carrello.getSelectedRow();
				if (rigaVista < 0) {
					JOptionPane.showMessageDialog(mainPanel, "Seleziona un prodotto dal carrello.",
							"Nessuna selezione", JOptionPane.WARNING_MESSAGE);
					return;
				}
				int riga = table_carrello.convertRowIndexToModel(rigaVista);
				long idProdotto = Long.parseLong(table_carrello.getModel().getValueAt(riga, 0).toString());
				long nuovaQuantita = ((Number) spinner_quantita.getValue()).longValue();

				if (nuovaQuantita == 0) {
					int scelta = JOptionPane.showConfirmDialog(mainPanel, "Rimuovere il prodotto dal carrello?",
							"Rimozione prodotto", JOptionPane.YES_NO_OPTION);
					if (scelta != JOptionPane.YES_OPTION) {
						return;
					}
				}

				boolean esito = ControllerCarrello.modificaQuantita(idCliente, idProdotto, nuovaQuantita);

				if (esito) {
					label_esito.setForeground(new Color(0, 128, 0));
					label_esito.setText("Carrello aggiornato");
					caricaCarrello();
				} else {
					label_esito.setForeground(Color.RED);
					label_esito.setText("Modifica non riuscita");
					JOptionPane.showMessageDialog(mainPanel, "Impossibile aggiornare la quantità.",
							"Modifica non riuscita", JOptionPane.WARNING_MESSAGE);
				}
			}
		});

		confermaButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				boolean esito = ControllerOrdini.confermaOrdine(idCliente);

				if (esito) {
					JOptionPane.showMessageDialog(mainPanel, "Ordine confermato!",
							"Ordine confermato", JOptionPane.INFORMATION_MESSAGE);
					caricaCarrello();
				} else {
					label_esito.setForeground(Color.RED);
					label_esito.setText("Ordine non confermato");
					JOptionPane.showMessageDialog(mainPanel, "Impossibile confermare: carrello vuoto o prodotti non più disponibili.",
							"Ordine non confermato", JOptionPane.WARNING_MESSAGE);
				}
			}
		});
	}

	public JFrame apriFormCarrello() {
		frame = new JFrame("Carrello");
		frame.setContentPane(mainPanel);
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		caricaCarrello();
		frame.pack();
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
		return frame;
	}

	private void caricaCarrello() {
		List<String[]> righe = ControllerCarrello.getCarrello(idCliente);
		String[] colonne = {"IdProdotto", "Nome", "Prezzo (€)", "Quantità", "Subtotale (€)"};
		DefaultTableModel model = new DefaultTableModel(colonne, 0) {
			@Override
			public boolean isCellEditable(int riga, int colonna) {
				return false;
			}
		};
		for (String[] riga : righe) {
			model.addRow(new String[]{riga[0], riga[1], riga[2], riga[3], formattaImporto(Double.parseDouble(riga[4]))});
		}
		table_carrello.setModel(model);
		table_carrello.removeColumn(table_carrello.getColumnModel().getColumn(0));
		double totale = righe.isEmpty() ? 0 : Double.parseDouble(righe.get(0)[5]);
		label_totale.setText("Totale: " + formattaImporto(totale) + " €");
		label_esito.setForeground(Color.DARK_GRAY);
		label_esito.setText(righe.isEmpty() ? "Il carrello è vuoto" : "Articoli nel carrello: " + righe.size());
	}

	private String formattaImporto(double importo) {
		return BigDecimal.valueOf(importo).setScale(2, RoundingMode.HALF_UP).toPlainString();
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(10, 10, 10, 10), -1, -1));
		mainPanel.setPreferredSize(new Dimension(650, 400));
		final JScrollPane scrollPane1 = new JScrollPane();
		mainPanel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		table_carrello = new JTable();
		scrollPane1.setViewportView(table_carrello);
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 5, new Insets(0, 0, 0, 0), -1, -1));
		mainPanel.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JLabel label1 = new JLabel();
		label1.setText("Nuova quantità:");
		panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		spinner_quantita = new JSpinner();
		panel1.add(spinner_quantita, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(60, -1), null, 0, false));
		modificaButton = new JButton();
		modificaButton.setText("Modifica quantità");
		panel1.add(modificaButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		panel1.add(spacer1, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		label_totale = new JLabel();
		label_totale.setText("Totale: 0.00 €");
		panel1.add(label_totale, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
		mainPanel.add(panel2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		aggiornaButton = new JButton();
		aggiornaButton.setText("Aggiorna");
		panel2.add(aggiornaButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer2 = new Spacer();
		panel2.add(spacer2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		label_esito = new JLabel();
		label_esito.setText("");
		panel2.add(label_esito, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		confermaButton = new JButton();
		confermaButton.setText("Procedi all'ordine");
		panel2.add(confermaButton, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}
}
