package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import control.ControllerOrdini;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class FormOrdini {
	private JPanel mainPanel;
	private JTable table_ordini;
	private JButton aggiornaButton;
	private JLabel label_esito;

	public FormOrdini() {
		aggiornaButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				caricaOrdini();
			}
		});
	}

	public JFrame apriFormOrdini() {
		JFrame frame = new JFrame("Gestione ordini");
		frame.setContentPane(mainPanel);
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		caricaOrdini();
		frame.pack();
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
		return frame;
	}

	private void caricaOrdini() {
		List<String[]> righe = ControllerOrdini.getOrdini();
		String[] colonne = {"Id", "Cliente", "Data", "Totale (€)", "Indirizzo di spedizione", "Stato"};
		DefaultTableModel model = new DefaultTableModel(colonne, 0) {
			@Override
			public boolean isCellEditable(int riga, int colonna) {
				return false;
			}
		};
		for (String[] riga : righe) {
			model.addRow(new String[]{riga[0], riga[5], riga[1], riga[2], riga[3], riga[4]});
		}
		table_ordini.setModel(model);
		table_ordini.setAutoCreateRowSorter(true);
		label_esito.setText(righe.isEmpty() ? "Nessun ordine da mostrare" : "Ordini totali: " + righe.size());
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
		mainPanel.setPreferredSize(new Dimension(700, 400));
		final JScrollPane scrollPane1 = new JScrollPane();
		mainPanel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		table_ordini = new JTable();
		scrollPane1.setViewportView(table_ordini);
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
		mainPanel.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		aggiornaButton = new JButton();
		aggiornaButton.setText("Aggiorna");
		panel1.add(aggiornaButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		panel1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		label_esito = new JLabel();
		label_esito.setText("");
		panel1.add(label_esito, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}
}
