package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import control.ControllerUtenti;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FormRegistrazione {
	private JPanel mainPanel;
	private JTextField textField_email;
	private JPasswordField passwordField;
	private JTextField textField_nome;
	private JTextField textField_cognome;
	private JTextField textField_indirizzo;
	private JTextField textField_immagine;
	private JButton confermaButton;
	private JLabel label_esito;

	private JFrame frame;

	public FormRegistrazione() {
		confermaButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				String email = textField_email.getText().trim();
				String password = new String(passwordField.getPassword());
				String nome = textField_nome.getText().trim();
				String cognome = textField_cognome.getText().trim();
				String indirizzo = textField_indirizzo.getText().trim();
				String percorsoImmagine = textField_immagine.getText().trim();

				if (email.isEmpty() || password.isEmpty() || nome.isEmpty() || cognome.isEmpty() || indirizzo.isEmpty()) {
					label_esito.setForeground(Color.RED);
					label_esito.setText("Compila tutti i campi obbligatori");
					JOptionPane.showMessageDialog(mainPanel, "Compila tutti i campi obbligatori.",
							"Dati mancanti", JOptionPane.WARNING_MESSAGE);
					return;
				}

				boolean esito = ControllerUtenti.registra(email, password, nome, cognome, indirizzo, percorsoImmagine);

				if (esito) {
					JOptionPane.showMessageDialog(mainPanel, "Registrazione completata. Effettua l'accesso.",
							"Registrazione completata", JOptionPane.INFORMATION_MESSAGE);
					frame.dispose();
				} else {
					label_esito.setForeground(Color.RED);
					label_esito.setText("Email già registrata");
					JOptionPane.showMessageDialog(mainPanel, "Email già registrata.",
							"Registrazione non riuscita", JOptionPane.WARNING_MESSAGE);
				}
			}
		});
	}

	public JFrame apriFormRegistrazione() {
		frame = new JFrame("Registrazione");
		frame.setContentPane(mainPanel);
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		frame.pack();
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
		return frame;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridLayoutManager(8, 2, new Insets(20, 20, 20, 20), -1, -1));
		mainPanel.setPreferredSize(new Dimension(420, 320));
		final JLabel label1 = new JLabel();
		label1.setText("Email *");
		mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		textField_email = new JTextField();
		mainPanel.add(textField_email, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label2 = new JLabel();
		label2.setText("Password *");
		mainPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		passwordField = new JPasswordField();
		mainPanel.add(passwordField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label3 = new JLabel();
		label3.setText("Nome *");
		mainPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		textField_nome = new JTextField();
		mainPanel.add(textField_nome, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label4 = new JLabel();
		label4.setText("Cognome *");
		mainPanel.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		textField_cognome = new JTextField();
		mainPanel.add(textField_cognome, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label5 = new JLabel();
		label5.setText("Indirizzo *");
		mainPanel.add(label5, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		textField_indirizzo = new JTextField();
		mainPanel.add(textField_indirizzo, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label6 = new JLabel();
		label6.setText("Immagine profilo");
		mainPanel.add(label6, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		textField_immagine = new JTextField();
		mainPanel.add(textField_immagine, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		label_esito = new JLabel();
		label_esito.setText("");
		mainPanel.add(label_esito, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		confermaButton = new JButton();
		confermaButton.setText("Registrati");
		mainPanel.add(confermaButton, new GridConstraints(7, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}
}
