package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import control.ControllerUtenti;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FormAccesso {
	private JPanel mainPanel;
	private JTextField textField_email;
	private JPasswordField passwordField;
	private JButton accediButton;
	private JButton registratiButton;
	private JLabel label_esito;

	private JFrame frame;
	private JFrame frameRegistrazione;

	public FormAccesso() {
		accediButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				String email = textField_email.getText().trim();
				String password = new String(passwordField.getPassword());

				if (email.isEmpty() || password.isEmpty()) {
					label_esito.setForeground(Color.RED);
					label_esito.setText("Compila tutti i campi");
					JOptionPane.showMessageDialog(mainPanel, "Compila tutti i campi.",
							"Dati mancanti", JOptionPane.WARNING_MESSAGE);
					return;
				}

				String[] risultato = ControllerUtenti.autentica(email, password);

				if (risultato == null) {
					label_esito.setForeground(Color.RED);
					label_esito.setText("Credenziali non valide");
					JOptionPane.showMessageDialog(mainPanel, "Credenziali non valide.",
							"Accesso non riuscito", JOptionPane.ERROR_MESSAGE);
					return;
				}

				long idUtente = Long.parseLong(risultato[0]);

				new MainFrame(idUtente, risultato[1]).apriMainFrame();
				frame.dispose();
			}
		});

		registratiButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				if (frameRegistrazione == null || !frameRegistrazione.isDisplayable()) {
					frameRegistrazione = new FormRegistrazione().apriFormRegistrazione();
				} else {
					frameRegistrazione.toFront();
					frameRegistrazione.requestFocus();
				}
			}
		});
	}

	public JFrame apriFormAccesso() {
		frame = new JFrame("E-commerce - Accesso");
		frame.setContentPane(mainPanel);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
		return frame;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridLayoutManager(5, 2, new Insets(20, 20, 20, 20), -1, -1));
		mainPanel.setPreferredSize(new Dimension(380, 200));
		final JLabel label1 = new JLabel();
		label1.setText("Benvenuto! Accedi per continuare");
		mainPanel.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JLabel label2 = new JLabel();
		label2.setText("Email");
		mainPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		textField_email = new JTextField();
		mainPanel.add(textField_email, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label3 = new JLabel();
		label3.setText("Password");
		mainPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		passwordField = new JPasswordField();
		mainPanel.add(passwordField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		label_esito = new JLabel();
		label_esito.setText("");
		mainPanel.add(label_esito, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		accediButton = new JButton();
		accediButton.setText("Accedi");
		mainPanel.add(accediButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		registratiButton = new JButton();
		registratiButton.setText("Registrati");
		mainPanel.add(registratiButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}
}
