package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import control.ControllerCarrello;
import control.ControllerProdotti;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class FormNegozio {
	private JPanel mainPanel;
	private JButton aggiornaButton;
	private JTable table_prodotti;
	private JLabel label_quantita;
	private JSpinner spinner_quantita;
	private JButton aggiungiButton;
	private JLabel label_esito;

	private final long idUtente;
	private final boolean soloLettura;

	public FormNegozio(long idUtente, boolean soloLettura) {
		this.idUtente = idUtente;
		this.soloLettura = soloLettura;
		spinner_quantita.setModel(new SpinnerNumberModel(1, 1, 999, 1));
		table_prodotti.setAutoCreateRowSorter(true);

		label_quantita.setVisible(!soloLettura);
		spinner_quantita.setVisible(!soloLettura);
		aggiungiButton.setVisible(!soloLettura);

		aggiornaButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				caricaCatalogo();
			}
		});

		if (soloLettura) {
			return;
		}

		aggiungiButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				int rigaVista = table_prodotti.getSelectedRow();
				if (rigaVista < 0) {
					JOptionPane.showMessageDialog(mainPanel, "Seleziona un prodotto dal catalogo.",
							"Nessuna selezione", JOptionPane.WARNING_MESSAGE);
					return;
				}
				int riga = table_prodotti.convertRowIndexToModel(rigaVista);
				long idProdotto = Long.parseLong(table_prodotti.getModel().getValueAt(riga, 0).toString());
				long quantita = ((Number) spinner_quantita.getValue()).longValue();

				int esito = ControllerCarrello.aggiungiAlCarrello(idUtente, idProdotto, quantita);

				switch (esito) {
					case ControllerCarrello.PRODOTTO_AGGIUNTO:
						label_esito.setForeground(new Color(0, 128, 0));
						label_esito.setText("Prodotto aggiunto al carrello");
						break;
					case ControllerCarrello.NON_AGGIUNGIBILE:
						label_esito.setForeground(Color.RED);
						label_esito.setText("Prodotto non aggiungibile");
						JOptionPane.showMessageDialog(mainPanel, "Prodotto non disponibile o quantità superiore alla disponibilità.",
								"Prodotto non aggiungibile", JOptionPane.WARNING_MESSAGE);
						break;
					case ControllerCarrello.PRODOTTO_NON_ESISTENTE:
						label_esito.setForeground(Color.RED);
						label_esito.setText("Prodotto non trovato");
						JOptionPane.showMessageDialog(mainPanel, "Prodotto non trovato. Aggiorna il catalogo.",
								"Prodotto non trovato", JOptionPane.ERROR_MESSAGE);
						break;
					case ControllerCarrello.QUANTITA_NON_VALIDA:
						label_esito.setForeground(Color.RED);
						label_esito.setText("Quantità non valida");
						JOptionPane.showMessageDialog(mainPanel, "Quantità non valida.",
								"Quantità non valida", JOptionPane.WARNING_MESSAGE);
						break;
					case ControllerCarrello.ERRORE_DI_SISTEMA:
					default:
						label_esito.setForeground(Color.RED);
						label_esito.setText("Errore di sistema");
						JOptionPane.showMessageDialog(mainPanel, "Errore di sistema. Riprova più tardi.",
								"Errore", JOptionPane.ERROR_MESSAGE);
						break;
				}
			}
		});
	}

	public JFrame apriFormNegozio() {
		JFrame frame = new JFrame(soloLettura ? "Catalogo prodotti" : "Negozio");
		frame.setContentPane(mainPanel);
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		caricaCatalogo();
		frame.pack();
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
		return frame;
	}

	private void caricaCatalogo() {
		List<String[]> righe = ControllerProdotti.getProdotti();
		String[] colonne = {"Id", "Nome", "Descrizione", "Prezzo (€)", "Quantità", "Disponibile", "In offerta", "Categoria"};
		DefaultTableModel model = new DefaultTableModel(colonne, 0) {
			@Override
			public boolean isCellEditable(int riga, int colonna) {
				return false;
			}
		};
		for (String[] riga : righe) {
			model.addRow(riga);
		}
		table_prodotti.setModel(model);
		table_prodotti.removeColumn(table_prodotti.getColumnModel().getColumn(0));
		label_esito.setForeground(Color.DARK_GRAY);
		label_esito.setText(righe.isEmpty() ? "Nessun prodotto in catalogo" : "Prodotti in catalogo: " + righe.size());
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(10, 10, 10, 10), -1, -1));
		mainPanel.setPreferredSize(new Dimension(900, 500));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		mainPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		aggiornaButton = new JButton();
		aggiornaButton.setText("Aggiorna");
		panel1.add(aggiornaButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		panel1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		final JScrollPane scrollPane1 = new JScrollPane();
		mainPanel.add(scrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		table_prodotti = new JTable();
		scrollPane1.setViewportView(table_prodotti);
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridLayoutManager(1, 5, new Insets(0, 0, 0, 0), -1, -1));
		mainPanel.add(panel2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		label_quantita = new JLabel();
		label_quantita.setText("Quantità:");
		panel2.add(label_quantita, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		spinner_quantita = new JSpinner();
		panel2.add(spinner_quantita, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(60, -1), null, 0, false));
		aggiungiButton = new JButton();
		aggiungiButton.setText("Aggiungi al carrello");
		panel2.add(aggiungiButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer2 = new Spacer();
		panel2.add(spacer2, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		label_esito = new JLabel();
		label_esito.setText("");
		panel2.add(label_esito, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}
}
