package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainFrame {
	private JPanel mainPanel;
	private JLabel lbl_welcome;
	private JButton catalogoButton;
	private JButton carrelloButton;
	private JButton ordiniButton;

	private final long idUtente;
	private final boolean amministratore;

	private JFrame frameNegozio;
	private JFrame frameCarrello;
	private JFrame frameOrdini;

	public MainFrame(long idUtente, String ruolo) {
		this.idUtente = idUtente;
		// L'amministratore è il caso esplicito: un ruolo inatteso non deve concedere
		// le sue funzioni, ma ricadere su quelle del cliente.
		this.amministratore = "AMMINISTRATORE".equals(ruolo);

		lbl_welcome.setText(amministratore ? "Benvenuto nell'area amministratore!" : "Benvenuto nell'area cliente!");
		carrelloButton.setVisible(!amministratore);

		catalogoButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				if (frameNegozio == null || !frameNegozio.isDisplayable()) {
					frameNegozio = new FormNegozio(idUtente, amministratore).apriFormNegozio();
				} else {
					frameNegozio.toFront();
					frameNegozio.requestFocus();
				}
			}
		});

		carrelloButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				if (frameCarrello == null || !frameCarrello.isDisplayable()) {
					frameCarrello = new FormCarrello(idUtente).apriFormCarrello();
				} else {
					frameCarrello.toFront();
					frameCarrello.requestFocus();
				}
			}
		});

		ordiniButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				if (frameOrdini == null || !frameOrdini.isDisplayable()) {
					frameOrdini = new FormOrdini(idUtente, amministratore).apriFormOrdini();
				} else {
					frameOrdini.toFront();
					frameOrdini.requestFocus();
				}
			}
		});
	}

	public JFrame apriMainFrame() {
		JFrame frame = new JFrame("E-commerce - Home");
		frame.setContentPane(mainPanel);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
		return frame;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridLayoutManager(2, 3, new Insets(20, 20, 25, 20), -1, -1));
		mainPanel.setPreferredSize(new Dimension(540, 130));
		lbl_welcome = new JLabel();
		lbl_welcome.setText("Benvenuto!");
		mainPanel.add(lbl_welcome, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		catalogoButton = new JButton();
		catalogoButton.setText("Catalogo prodotti");
		mainPanel.add(catalogoButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(230, 34), null, 0, false));
		carrelloButton = new JButton();
		carrelloButton.setText("Il mio carrello");
		mainPanel.add(carrelloButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(230, 34), null, 0, false));
		ordiniButton = new JButton();
		ordiniButton.setText("Storico ordini");
		mainPanel.add(ordiniButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(230, 34), null, 0, false));
	}

	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}
}
